on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

name: Check multiple ACT-OTN matches

jobs:
  check_it:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      MATOS_USER: ${{ secrets.MATOS_USERNAME }}
      MATOS_PASS: ${{ secrets.MATOS_PASSWORD }}

    steps:
      - name: Check out GH repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat

      - name: Check test-list_projects
        shell: Rscript {0}
        run: |
          testthat::test_file('tests/testthat/test-list_projects.R')

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
